name: S3 Sync

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - "src/assets/*"

permissions:
  id-token: write
  contents: read

jobs:
  s3-sync:
    name: Synchronize static assets to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          role-session-name: interop-landing-numbers-page-s3-sync-${{ github.run_number }}

      - name: Sync files to S3
        run: |
          aws s3 sync src/assets/ s3://${{ vars.s3_bucket_name }}/assets/ --delete
